version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
    # Specify labels for pull requests
    labels:
      - 'dependencies'
      - 'npm'
    # Set version update strategy
    versioning-strategy: auto
    # Limit the number of open pull requests
    open-pull-requests-limit: 10
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - '*'
    # Allow up-to-date branches to be rebased
    rebase-strategy: auto
    # Specify the version update behavior
    ignore:
      # Ignore major version updates
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
